# Generated by Django 4.1.4 on 2022-12-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_post_featured_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
